title: Craig Talk
logo: "" # You can add own logo image.
description: Minimalistic Theme for Jekyll
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://talk.craigary.net" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Craig Hart
  bio: Hi.

# Contact links
twitter: https://twitter.com/craigaryhart # Add your Twitter handle
weibo: https://weibo.com/236682349
instagram: https://instagram.com/craigaryhart # Add your Instagram handle
github: https://github.com/craigary
rss: feed.xml
email: i@craigary.net # Add your Email address

# Hero Section
hero: false # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Raked Minimalistic Theme # Add your hero title
hero-subtitle: For those who love simplicity # Add your hero subtitle
hero-image: images/14.jpg # Add background image in section hero

# Footer
footer-image: images/14.jpg # Add background image in footer

# Comment Section (isso)
enable-comments: true # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
enable-newsletter: false
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed